spring:
  application:
    name: student
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:sqlserver://azureroot.database.windows.net.database.windows.net:1433;database=student;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: heshan@azureroot.database.windows.net
    password: 123456789hH
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

eureka:
  instance:
    hostname: azureroot.database.windows.net
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
