eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070

spring:
  application:
    name: schools
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;databaseName=azuresqlserverlk/school;encrypt=true;trustServerCertificate=false
#    username: heshan@azuresqlserverlk
#    password: 123456789hH

#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.SQLServer2012Dialect

application:
  config:
    students-url: http://localhost:8222/api/v1/students

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
